apiVersion: v1
kind: Secret

metadata:
  name: url-shortener-secret

type: Opaque

stringData:
  MONGODB_URI: <replace-with-mongodb-uri>
  JWT_SECRET: <replace-with-jwt-secret>
  FRONTEND_URL: <replace-with-frontend-url>